"""PrusaSlicer pipeline for the tutor: slice, check, render, see the GUI, copy to USB.

Author: Dennel04 (with the tutor), 2026-10-04. Shared for the team on 2026-10-04.
Stdlib + Pillow only. Run from the fusion-tutor folder: python shared/tools/prusa/prusa.py ...

  python prusa.py profile <file.bgcode|.gcode|.3mf> [--name team-coreone-hf04]
  python prusa.py slice <model.stl|.3mf> [--profile NAME] [--supports buildplate|everywhere|off]
                  [--style organic|grid|snug] [--rotate-x DEG] [--rotate-y DEG] [--rotate-z DEG]
                  [--set key=value ...] [--name BASE] [--out DIR] [--usb]
  python prusa.py check <file.gcode>          # report from a text G-code
  python prusa.py render <file.gcode> [-o out.png]
  python prusa.py screen [--title PrusaSlicer|"G-code Viewer"] [-o out.png]
  python prusa.py open <file>                 # .gcode/.bgcode -> G-code Viewer, else PrusaSlicer
  python prusa.py usb <file> [--as NAME]      # copy to the PRUSA USB stick, verify sha256

Why a text G-code next to every .bgcode: .bgcode is compressed (MeatPack/heatshrink),
so checks and renders run on a text twin kept in the cache, never on a guess.
"""
import argparse, hashlib, os, re, shutil, struct, subprocess, sys, tempfile, time, zipfile, zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROFILES = HERE / "profiles"
CACHE = Path(os.environ.get("LOCALAPPDATA", tempfile.gettempdir())) / "fusion-tutor" / "prusa"
PS_DIR = Path(os.environ.get("PRUSA_SLICER_DIR", r"C:\Program Files\Prusa3D\PrusaSlicer"))
PS_CLI = PS_DIR / "prusa-slicer-console.exe"
PS_GUI = PS_DIR / "prusa-slicer.exe"
PS_VIEWER = PS_DIR / "prusa-gcodeviewer.exe"
DEFAULT_PROFILE = "team-coreone-hf04"

# ---------------------------------------------------------------- config I/O

def _bgcode_slicer_config(data: bytes) -> str:
    """Return the slicer-metadata block (full config, key=value) of a .bgcode."""
    _magic, _ver, ck = struct.unpack_from("<4sIH", data, 0)
    p = 10
    while p < len(data):
        typ, comp, usize = struct.unpack_from("<HHI", data, p)
        p += 8
        csize = usize
        if comp:
            csize = struct.unpack_from("<I", data, p)[0]
            p += 4
        params = 6 if typ == 5 else 2
        block = data[p + params:p + params + csize]
        if typ == 2:
            if comp == 1:
                return zlib.decompress(block).decode("utf-8")
            if comp == 0:
                return block.decode("utf-8")
            raise SystemExit(f"slicer metadata uses compression {comp}; only deflate is supported")
        p += params + csize + (4 if ck == 1 else 0)
    raise SystemExit("no slicer metadata block in this .bgcode")


def parse_config(text: str) -> dict:
    cfg = {}
    for line in text.splitlines():
        m = re.match(r"^\s*;?\s*([A-Za-z0-9_]+)\s*=\s?(.*)$", line)
        if m:
            cfg[m.group(1)] = m.group(2)
    return cfg


def read_config(path: Path) -> dict:
    suf = path.suffix.lower()
    if suf == ".bgcode":
        return parse_config(_bgcode_slicer_config(path.read_bytes()))
    if suf == ".3mf":
        with zipfile.ZipFile(path) as z:
            if "Metadata/Slic3r_PE.config" not in z.namelist():
                raise SystemExit(f"{path.name}: no print settings inside (model-only 3MF)")
            return parse_config(z.read("Metadata/Slic3r_PE.config").decode("utf-8"))
    if suf == ".gcode":
        text = path.read_text(encoding="utf-8", errors="replace")
        i = text.rfind("; prusaslicer_config = begin")
        if i < 0:
            raise SystemExit(f"{path.name}: no PrusaSlicer config block at the end")
        return parse_config(text[i:])
    if suf == ".ini":
        return parse_config(path.read_text(encoding="utf-8"))
    raise SystemExit(f"don't know how to read a config from {suf}")


def write_ini(cfg: dict, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(f"{k} = {cfg[k]}\n" for k in sorted(cfg)), encoding="utf-8", newline="\n")


def embed_config_in_3mf(path: Path, cfg: dict):
    """PrusaSlicer's CLI writes model-only 3MF; add the settings so the GUI opens it as a project."""
    text = "; generated by PrusaSlicer\n\n" + "".join(f"; {k} = {cfg[k]}\n" for k in sorted(cfg))
    tmp = path.with_suffix(".3mf.tmp")
    with zipfile.ZipFile(path) as zi, zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zo:
        for n in zi.namelist():
            if n != "Metadata/Slic3r_PE.config":
                zo.writestr(n, zi.read(n))
        zo.writestr("Metadata/Slic3r_PE.config", text)
    tmp.replace(path)

# ---------------------------------------------------------------- G-code analysis

MOVE = re.compile(r"^G[01]\s")
AX = re.compile(r"([XYZE])(-?\d*\.?\d+)")


def parse_gcode(path: Path):
    """Yield segments (x0,y0,x1,y1,z,type) for extruding moves, plus header stats."""
    segs, stats = [], {}
    x = y = z = 0.0
    rel_e = True
    typ = "Unknown"
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith(";TYPE:"):
                typ = line[6:].strip()
                continue
            if line.startswith("; ") and "=" in line:
                k, _, v = line[2:].partition("=")
                k = k.strip()
                if k in ("filament used [g]", "estimated printing time (normal mode)",
                         "filament used [mm]", "print_settings_id", "printer_settings_id",
                         "filament_settings_id", "support_material", "support_material_style",
                         "support_material_buildplate_only", "layer_height", "max_layer_z"):
                    stats[k] = v.strip()
                continue
            if line.startswith("M82"):
                rel_e = False
            elif line.startswith("M83"):
                rel_e = True
            if not MOVE.match(line):
                continue
            vals = dict(AX.findall(line.split(";")[0]))
            nx = float(vals.get("X", x)); ny = float(vals.get("Y", y)); nz = float(vals.get("Z", z))
            e = float(vals["E"]) if "E" in vals else 0.0
            if e > 0 and rel_e and (nx != x or ny != y):
                segs.append((x, y, nx, ny, nz, typ))
            x, y, z = nx, ny, nz
    return segs, stats


def report(path: Path) -> str:
    segs, st = parse_gcode(path)
    segs = [s for s in segs if s[5] != "Custom"]  # purge line of the start G-code
    if not segs:
        return "no extrusion found"
    by_type = {}
    for s in segs:
        by_type.setdefault(s[5], []).append(s)
    zs = sorted({s[4] for s in segs})
    first_z = zs[0]
    first = [s for s in segs if s[4] == first_z]
    fx = [v for s in first for v in (s[0], s[2])]
    fy = [v for s in first for v in (s[1], s[3])]
    ax = [v for s in segs for v in (s[0], s[2])]
    ay = [v for s in segs for v in (s[1], s[3])]
    lines = [
        f"file: {path.name}",
        f"printer: {st.get('printer_settings_id', '?')} | print: {st.get('print_settings_id', '?')} | filament: {st.get('filament_settings_id', '?')}",
        f"time: {st.get('estimated printing time (normal mode)', '?')} | filament: {st.get('filament used [g]', '?')} g",
        f"layers: {len(zs)} | height: {zs[-1]:.2f} mm | footprint X {min(ax):.1f}..{max(ax):.1f}  Y {min(ay):.1f}..{max(ay):.1f}",
        f"first layer z={first_z:.2f}: {len(first)} segments, X {min(fx):.1f}..{max(fx):.1f}  Y {min(fy):.1f}..{max(fy):.1f}, types {sorted({s[5] for s in first})}",
    ]
    sup = by_type.get("Support material", []) + by_type.get("Support material interface", [])
    if sup:
        sz = sorted({s[4] for s in sup})
        lines.append(f"SUPPORTS: yes, {len(sz)} layers, z {sz[0]:.2f}..{sz[-1]:.2f} "
                     f"(style {st.get('support_material_style', '?')}, build plate only {st.get('support_material_buildplate_only', '?')})")
    else:
        lines.append("SUPPORTS: none")
    ov = len(by_type.get("Overhang perimeter", []))
    lines.append(f"overhang perimeter segments: {ov}")
    lines.append("feature segments: " + ", ".join(f"{k} {len(v)}" for k, v in sorted(by_type.items())))
    return "\n".join(lines)

# ---------------------------------------------------------------- rendering

COLORS = {
    "Perimeter": (255, 230, 77), "External perimeter": (255, 125, 56), "Overhang perimeter": (31, 31, 255),
    "Internal infill": (176, 48, 41), "Solid infill": (150, 84, 204), "Top solid infill": (240, 64, 64),
    "Bridge infill": (77, 128, 186), "Gap fill": (255, 255, 255), "Skirt/Brim": (0, 135, 110),
    "Support material": (0, 200, 0), "Support material interface": (0, 110, 0), "Custom": (90, 90, 90),
}


def render(path: Path, out: Path) -> Path:
    from PIL import Image, ImageDraw
    segs, st = parse_gcode(path)
    segs = [q for q in segs if q[5] != "Custom"]  # purge line would shrink the part to a dot
    if not segs:
        raise SystemExit("nothing to render")
    W, H, M = 760, 560, 30
    import math
    c, s = math.cos(math.radians(30)), math.sin(math.radians(30))
    views = {
        "iso": lambda x, y, z: ((x - y) * c, -((x + y) * s) - z),
        "front (X-Z)": lambda x, y, z: (x, -z),
        "side (Y-Z)": lambda x, y, z: (y, -z),
    }
    zs = sorted({q[4] for q in segs})
    panels = []
    for name, f in views.items():
        pts = [f(q[0], q[1], q[4]) for q in segs] + [f(q[2], q[3], q[4]) for q in segs]
        minx = min(p[0] for p in pts); maxx = max(p[0] for p in pts)
        miny = min(p[1] for p in pts); maxy = max(p[1] for p in pts)
        k = min((W - 2 * M) / (maxx - minx or 1), (H - 2 * M) / (maxy - miny or 1))
        img = Image.new("RGB", (W, H), (40, 40, 40))
        d = ImageDraw.Draw(img)
        order = segs if name == "iso" else sorted(segs, key=lambda q: q[5].startswith("Support"))
        for q in order:
            a = f(q[0], q[1], q[4]); b = f(q[2], q[3], q[4])
            d.line([(M + (a[0] - minx) * k, M + (a[1] - miny) * k), (M + (b[0] - minx) * k, M + (b[1] - miny) * k)],
                   fill=COLORS.get(q[5], (200, 200, 200)), width=1)
        d.text((8, 6), name, fill=(255, 255, 255))
        panels.append(img)
    # first layer, top view
    first = [q for q in segs if q[4] == zs[0]]
    xs = [v for q in segs for v in (q[0], q[2])]; ys = [v for q in segs for v in (q[1], q[3])]
    k = min((W - 2 * M) / (max(xs) - min(xs) or 1), (H - 2 * M) / (max(ys) - min(ys) or 1))
    img = Image.new("RGB", (W, H), (40, 40, 40))
    d = ImageDraw.Draw(img)
    for q in segs:  # ghost of the whole part
        d.line([(M + (q[0] - min(xs)) * k, H - M - (q[1] - min(ys)) * k), (M + (q[2] - min(xs)) * k, H - M - (q[3] - min(ys)) * k)], fill=(70, 70, 70))
    for q in first:
        d.line([(M + (q[0] - min(xs)) * k, H - M - (q[1] - min(ys)) * k), (M + (q[2] - min(xs)) * k, H - M - (q[3] - min(ys)) * k)],
               fill=COLORS.get(q[5], (200, 200, 200)), width=2)
    d.text((8, 6), f"first layer z={zs[0]:.2f} (top view, grey = whole part)", fill=(255, 255, 255))
    panels.append(img)
    sheet = Image.new("RGB", (W * 2, H * 2 + 40), (25, 25, 25))
    for i, p in enumerate(panels):
        sheet.paste(p, ((i % 2) * W, (i // 2) * H))
    d = ImageDraw.Draw(sheet)
    used = sorted({q[5] for q in segs})
    xpos = 8
    for t in used:
        d.rectangle([xpos, H * 2 + 14, xpos + 12, H * 2 + 26], fill=COLORS.get(t, (200, 200, 200)))
        d.text((xpos + 16, H * 2 + 14), t, fill=(230, 230, 230))
        xpos += 22 + 7 * len(t)
    out.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(out)
    return out

# ---------------------------------------------------------------- GUI eyes

def screen(title: str, out: Path) -> Path:
    import ctypes
    from ctypes import wintypes
    from PIL import ImageGrab
    u = ctypes.windll.user32
    try:
        ctypes.windll.shcore.SetProcessDpiAwareness(2)
    except Exception:
        u.SetProcessDPIAware()
    found = []

    def cb(hwnd, _):
        if u.IsWindowVisible(hwnd):
            n = u.GetWindowTextLengthW(hwnd)
            buf = ctypes.create_unicode_buffer(n + 1)
            u.GetWindowTextW(hwnd, buf, n + 1)
            if title.lower() in buf.value.lower():
                found.append((hwnd, buf.value))
        return True
    u.EnumWindows(ctypes.WINFUNCTYPE(ctypes.c_bool, wintypes.HWND, wintypes.LPARAM)(cb), 0)
    if not found:
        raise SystemExit(f"no visible window with '{title}' in the title")
    hwnd, name = found[0]
    if u.IsIconic(hwnd):
        u.ShowWindow(hwnd, 9)  # SW_RESTORE
    u.SetForegroundWindow(hwnd)
    time.sleep(0.6)
    r = wintypes.RECT()
    u.GetWindowRect(hwnd, ctypes.byref(r))
    img = ImageGrab.grab(bbox=(r.left, r.top, r.right, r.bottom), all_screens=True)
    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out)
    print(f"window: {name}")
    return out

# ---------------------------------------------------------------- slicing

def fmt_minutes(t: str) -> str:
    d = dict((u, int(v)) for v, u in re.findall(r"(\d+)([dhms])", t))
    mins = d.get("d", 0) * 1440 + d.get("h", 0) * 60 + d.get("m", 0) + (1 if d.get("s", 0) >= 30 else 0)
    return f"{mins // 60}h{mins % 60}m" if mins >= 60 else f"{mins}m"


def run_cli(args):
    r = subprocess.run([str(PS_CLI), *args], capture_output=True, text=True, timeout=900)
    if r.returncode != 0:
        sys.stderr.write(r.stdout[-3000:] + r.stderr[-3000:])
        raise SystemExit(f"PrusaSlicer CLI failed ({r.returncode})")
    return r.stdout


def slice_cmd(a):
    model = Path(a.model).resolve()
    prof = PROFILES / f"{a.profile}.ini"
    if not prof.exists():
        raise SystemExit(f"profile {prof} missing: run `prusa.py profile <old print file>` first")
    out = Path(a.out).resolve() if a.out else model.parent
    out.mkdir(parents=True, exist_ok=True)
    base = a.name or model.stem
    opts = ["--load", str(prof)]
    # boolean options are flags in the CLI: --opt / --no-opt
    if a.supports == "off":
        opts += ["--no-support-material"]
    elif a.supports:
        opts += ["--support-material", "--support-material-auto",
                 "--support-material-buildplate-only" if a.supports == "buildplate"
                 else "--no-support-material-buildplate-only"]
    if a.style:
        opts += ["--support-material-style", a.style]
    for ax in ("x", "y", "z"):
        v = getattr(a, f"rotate_{ax}")
        if v:
            opts += [f"--rotate-{ax}" if ax != "z" else "--rotate", str(v)]
    for kv in a.set or []:
        k, _, v = kv.partition("=")
        flag = k.strip().replace("_", "-")
        if v.strip() in ("on", "off"):  # booleans: ironing=on (not 1/0: perimeters=1 is a number)
            opts += [f"--{flag}" if v.strip() == "on" else f"--no-{flag}"]
        else:
            opts += [f"--{flag}", v.strip()]
    opts += ["--center", a.center]
    CACHE.mkdir(parents=True, exist_ok=True)
    text = CACHE / f"{base}.gcode"
    run_cli([*opts, "--export-gcode", "--no-binary-gcode", "-o", str(text), str(model)])
    cfg = read_config(text)
    _, st = parse_gcode(text)
    meta = f"{cfg.get('nozzle_diameter', '0.4')}n_{cfg.get('layer_height', '0.2')}mm_{cfg.get('filament_type', 'PLA').split(';')[0]}_{cfg.get('printer_model', 'PRINTER')}"
    bg = out / f"{base}_{meta}_{fmt_minutes(st.get('estimated printing time (normal mode)', '0m'))}.bgcode"
    run_cli([*opts, "--export-gcode", "--binary-gcode", "-o", str(bg), str(model)])
    proj = out / f"{base}-sliced.3mf"
    run_cli([*opts, "--export-3mf", "-o", str(proj), str(model)])
    embed_config_in_3mf(proj, cfg)
    png = render(text, CACHE / f"{base}.png")
    rep = report(text)
    print(rep)
    print(f"\nbgcode : {bg}\nproject: {proj}\ntext   : {text}\npreview: {png}")
    if a.usb:
        usb(bg, None)


def find_usb() -> Path:
    r = subprocess.run(["powershell", "-NoProfile", "-Command",
                        "Get-Volume | Where-Object DriveType -eq 'Removable' | ForEach-Object { \"$($_.DriveLetter)|$($_.FileSystemLabel)\" }"],
                       capture_output=True, text=True)
    vols = [l.split("|") for l in r.stdout.split() if "|" in l and l[0].isalpha()]
    prusa = [v for v in vols if "PRUSA" in v[1].upper()] or vols
    if not prusa:
        raise SystemExit("no USB stick found")
    return Path(f"{prusa[0][0]}:\\")


def usb(src: Path, name):
    dst = find_usb() / (name or src.name)
    shutil.copyfile(src, dst)
    h = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()
    ok = h(src) == h(dst)
    print(f"USB: {dst}  sha256 {'OK' if ok else 'MISMATCH'}")
    if not ok:
        raise SystemExit(1)

# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("profile"); p.add_argument("file"); p.add_argument("--name", default=DEFAULT_PROFILE)
    p = sub.add_parser("slice"); p.add_argument("model")
    p.add_argument("--profile", default=DEFAULT_PROFILE)
    p.add_argument("--supports", choices=["buildplate", "everywhere", "off"])
    p.add_argument("--style", choices=["organic", "grid", "snug"])
    for ax in "xyz":
        p.add_argument(f"--rotate-{ax}", type=float, default=0)
    p.add_argument("--set", action="append", help="any PrusaSlicer option, e.g. perimeters=3")
    p.add_argument("--center", default="125,110")
    p.add_argument("--name"); p.add_argument("--out"); p.add_argument("--usb", action="store_true")
    p = sub.add_parser("check"); p.add_argument("file")
    p = sub.add_parser("render"); p.add_argument("file"); p.add_argument("-o")
    p = sub.add_parser("screen"); p.add_argument("--title", default="PrusaSlicer"); p.add_argument("-o")
    p = sub.add_parser("open"); p.add_argument("file")
    p = sub.add_parser("usb"); p.add_argument("file"); p.add_argument("--as", dest="as_name")
    a = ap.parse_args()

    if a.cmd == "profile":
        cfg = read_config(Path(a.file))
        dst = PROFILES / f"{a.name}.ini"
        write_ini(cfg, dst)
        print(f"{dst}: {len(cfg)} keys | {cfg.get('printer_settings_id')} | {cfg.get('print_settings_id')} | {cfg.get('filament_settings_id')}")
    elif a.cmd == "slice":
        slice_cmd(a)
    elif a.cmd == "check":
        print(report(Path(a.file)))
    elif a.cmd == "render":
        f = Path(a.file)
        print(render(f, Path(a.o) if a.o else CACHE / f"{f.stem}.png"))
    elif a.cmd == "screen":
        safe = re.sub(r"\W+", "_", a.title)
        print(screen(a.title, Path(a.o) if a.o else CACHE / f"screen_{safe}_{int(time.time())}.png"))
    elif a.cmd == "open":
        f = Path(a.file).resolve()
        exe = PS_VIEWER if f.suffix.lower() in (".gcode", ".bgcode") else PS_GUI
        subprocess.Popen([str(exe), str(f)])
        print(f"opened {f.name} in {exe.name}")
    elif a.cmd == "usb":
        usb(Path(a.file), a.as_name)


if __name__ == "__main__":
    main()
